[exclude]
directories = ["tests"]
types = ["exception"]
methods = ["magic"]
relationships = []
classes = []

[exception]
name = "*Exception"

[focus]
is_enable = true
root = "Visitor"
type = "all" # outgoing, incoming, all
depths = 1